<a href="https://colab.research.google.com/github/BabritB/step-by-step-ml-beginner/blob/master/Data_Preprocessing_Scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing the data 

### Basically scaling the datapoint values to normalize and have a fast processing and reduce computaional cost.
##### 1.Standardize numerical data (e.g. mean of 0 and standard deviation of 1) using the scale and center options.
##### 2.Normalize numerical data (e.g. to a range of 0-1) using the range option.

In [0]:
# Standardize data (0 mean, 1 stdev)

In [0]:
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

In [0]:
url = "https://goo.gl/bDdBiA"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [0]:
dataframe = pd.read_csv(url, names=names)

In [0]:
array = dataframe.values

In [7]:
print(array)

[[  6.    148.     72.    ...   0.627  50.      1.   ]
 [  1.     85.     66.    ...   0.351  31.      0.   ]
 [  8.    183.     64.    ...   0.672  32.      1.   ]
 ...
 [  5.    121.     72.    ...   0.245  30.      0.   ]
 [  1.    126.     60.    ...   0.349  47.      1.   ]
 [  1.     93.     70.    ...   0.315  23.      0.   ]]


In [0]:
# separate array into input and output components

In [0]:
X = array[:,0:8]
Y = array[:,8]

In [0]:
scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)

In [11]:
print(X)

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]


In [12]:
print(rescaledX)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]


In [0]:
# summarize transformed data
np.set_printoptions(precision=3)

In [15]:
print(rescaledX[0:5,:])

[[ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042]
 [-1.142  0.504 -1.505  0.907  0.766  1.41   5.485 -0.02 ]]


#### Scaling can be done to specific columns or features also depending on the required scenario. It is not necessary to scale all the features of the data set. We will undertand it more one we will start working with some feature engineering concepts. Above is just an example that how we are reducing the magnitude of the data point for better and faster calculations.